# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

experiment_name: noise

# environment/computational parameters
seed: [7028124]
device: cuda
num_workers: 4

# dataset parameters
data_root: C:\Users\au761482\OneDrive - Aarhus universitet\Documents\GitHub_repos\CV-eDNA-Hybrid\Data\Model_Data
annotate_root: annotations
img_path: Images
train_name: train_noise
val_name: valid_noise
class_labels: longlab
short_labels: order_plus
file_name: Label
num_classes: 17
data_cols: [86, 103]
num_col: 17


# training hyperparameters
image_size: [224, 224]
num_epochs: 100
batch_size: 128
learning_rate: 0.0001
weight_decay: 0.001
hidden_size: 128